Return-path: <gluck@mail.subscribe.ru>
Received: from [10.10.18.71] (helo=frv71.fwdcdn.com) by frv53.fwdcdn.com; Sat, 31 Mar 2018 11:35:25 +0300
Authentication-Result: IP=185.138.182.26; mail.from=gluck@mail.subscribe.ru; dkim=pass header.i= header.d=mail.bsndsy.ru; ID=1f2Byu-000NIH-RU
Received-SPF: pass (frv71.fwdcdn.com: domain of mail.subscribe.ru designates 185.138.182.26 as permitted sender) client-ip=185.138.182.26; envelope-from=gluck@mail.subscribe.ru; helo=gato26.sndsy.ru;
Received: from gato26.sndsy.ru ([185.138.182.26])
	by frv71.fwdcdn.com with esmtps ID 1f2Byu-000NIH-RU
	for xserge@ukr.net; Sat, 31 Mar 2018 11:35:24 +0300
Received: id 656B88B5960-1522485283
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=mail.bsndsy.ru; s=sndsy201706;
	t=1522485283; bh=V+T/4rFzbcsRkun6LKIJnSMGRURJoiaq9eFPpPQXv8o=;
	h=List-Id:List-Help:List-Subscribe:List-Unsubscribe:List-Archive:
	 List-Owner:List-Post:Message-Id:Date:From:To:X-Mailru-Msgtype:
	 Subject:MIME-Version:Content-Type;
	b=ZZKkQo4Z2/VX5QGF+4JSY7Tvwhn269C7TncuuAU1E/sve9HaiFqjt01o2cF3XI1Yp
	 QEl5ea01lylA7flgs00LzFUBBBRtULczuHxjS4r6Pv2RCEdDMd5VUhR6DgOnicZL6n
	 P5VD02k+jRRn8d2eQUQKasXO75XEOrwepI3y7T70=
List-Id: <rest.joke.vmestopps.subscribe.ru>
List-Help: <https://subscribe.ru/catalog/rest.joke.vmestopps>
List-Subscribe: <mailto:rest.joke.vmestopps-sub@subscribe.ru>
List-Unsubscribe: <mailto:rest.joke.vmestopps-unsub@subscribe.ru>
List-Archive: <https://subscribe.ru/archive/rest.joke.vmestopps>
List-Owner: <mailto:rest.joke.vmestopps-owner@subscribe.ru>
List-Post: NO
Message-Id: <20180331113122.hux.24424259@24424259.rest.joke.vmestopps.subscribe>
Date: Sat, 31 Mar 2018 11:31:22 +0300
From: =?utf-8?Q?=22Subscribe=2ERu=22?= <namma24424259@subscribe.ru>
To: "rest.joke.vmestopps" <xserge@ukr.net> (24424259)
X-Mailru-Msgtype: rest.joke.vmestopps 
Subject: =?utf-8?Q?=D0=92=D0=BC=D0=B5=D1=81=D1=82=D0=BE=20?=
 =?utf-8?Q?P=2EP=2ES=2E=20?=
 =?utf-8?Q?=D0=92=D1=8B=D0=BF=D1=83=D1=81=D0=BA=20?=
 =?utf-8?Q?=E2=84=963830=20?=
 =?utf-8?Q?=D0=BE=D1=82=20?=
 =?utf-8?Q?31=2E03=2E2018?=
MIME-Version: 1.0
Content-Type: text/html;
  charset="utf-8"
X-Authentication-Results: mxs.ukr.net;
		dkim=pass  header.i= header.d=mail.bsndsy.ru envelope-from=gluck@mail.subscribe.ru;
		spf=pass (frv71.fwdcdn.com: domain of mail.subscribe.ru designates 185.138.182.26 as permitted sender) client-ip=185.138.182.26;
		dmarc=accept header-from=namma24424259@subscribe.ru
X-Ukrnet-Yellow: 1
X-Ukrnet-Flavor: coconut
X-Antivirus: Avast (VPS 180401-0, 01.04.2018), Inbound message
X-Antivirus-Status: Clean


    
<!--
~~*~~
-->
            
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!--[if !mso]><!-->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!--<![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
        <meta name="keywords" content="блистать грань россыпь прикольный афоризм цитата фразочка любить оригинальный подписывать письмо остроумный поддерживать беседа слово
подарки отдых знакомства цветы" />
    <meta name="author" content="hohmochki@mail.ru автор и ведущий рассылки Хохмочки" />
                <link rel="Shortcut Icon" type="image/x-icon" href="https://subscribe.ru/img/favicon.ico" />
        
    <title>Subscribe.Ru : Вместо P.P.S. Выпуск №3830 от 31.03.2018</title>
    <style type="text/css"><!-- a:link
{
	color: #900000; 
}
a:visited    { color: #2F0000 }
a:active     { color: #FF0000 }
body         { font-family: Times New Roman; background-color: #ebd2a5; color: #2F0000 }
hr           { height: 1; color: #900000 }
hr#2           { height: 2; color: #900000 }
table
{
   border-color: #900000;
}
h1, h2, h3, h4, h5, h6
{
	font-family: Arial Rounded MT Bold, Arial, Helvetica;
}
h1           { color: #2F0000 }
h2
{
	color: #2F0000; 
}
h3
{
	color: #2F0000; 
}
h4
{
	color: #2F0000;
}
h5
{
	color: #2F0000;
}
h6
{
	color: #2F0000;
} --></style>    <!--[if (gte mso 9)|(IE)]>
    <style type="text/css">
        table {border-collapse: collapse !important;}
    </style>
    <![endif]-->
    <style>
        @media only screen and (max-device-width: 800px) {
            body { background-color: #ffffff; }
        }
    </style>
</head>
<body style="margin:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;min-width:100%;background-color:#f5f7f8;" >
<!--main center tag-->
<center style="width:100%;table-layout:fixed;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;" lang="x-another">
            
                    <!-- 532614 -->

<tr><td><font size="1" face="Arial, Helvetica, sans-serif" style="font-size: 8px;">&nbsp;&nbsp;</font></td></tr>
<tr><td bgcolor="#ffffff" style="background-color:#ffffff; background-image:none; padding:0; margin:0;">

<table width="100%" border="0" cellspacing="0" cellpadding="0" style="background-image:none; padding:0; margin:0;">
<tr>
 <td bgcolor="#ffffff" style="background-color:#ffffff; background-image:none; padding:0; margin:0;" align="center">
 
<table width="100%" border="0" cellspacing="6" cellpadding="0" style="background-image:none; padding:0; margin:0;"><tr><td align="center" style="background-color:#ffffff; font-size:13px; background-image:none; padding:0; margin:0;">
<a href="http://subs.link.subscribe.ru/subscribe/659880/24424259/rest.joke.vmestopps,37549/20180331113122/1WTGNMl0RIa2kpHjkx7Zqwnaminuan" style="text-decoration:none"><font face="Trebuchet MS, Arial, Helvetica, sans-serif" color="#1c70a0" size="2" style="font-size:13px"><b>MINI-MBA Intensive ваш
стремительный карьерный рост всего за 3 месяца! Только сейчас - 50%.</b></font></a>
</td></tr></table>

   
</td>
</tr>
</table>


</td></tr>

<tr><td><font size="1" face="Arial, Helvetica, sans-serif" style="font-size: 8px;">&nbsp;&nbsp;</font></td></tr>
<tr><td height="1" bgcolor="#b7b7b7"></td></tr>



            <!--Реклама 600х90-->
                                <table class="pack_hide" style="margin: 0 auto;"><TR><TD>
                    </TD></TR></table>
                        
                <!--shapka-->
        <div style="max-width:800px; margin:0 auto; margin-top:0px;" >
            <!--[if (gte mso 9)|(IE)]>
            <table width="800" align="center" style="border-spacing:0;" >
                <tr>
                    <td style="padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
            <![endif]-->
            
            <table align="center" cellspacing="0" cellpadding="0" border="0" style="border-spacing:0;margin:0 auto;width:100%;max-width:800px;" >
                <tbody>
                <tr>
                    <td bgcolor="#d8dde0" style="padding-top:0px;padding-bottom:0px;padding-right:0px;padding-left:0px;text-align:left;font-size:0;" >
            <!--[if (gte mso 9)|(IE)]>
            <table width="100%" style="border-spacing:0;" >
                <tr>
                    <td width="150" valign="top" style="padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
            <![endif]-->
            <table style="border-spacing:0;width:100%;display:inline-block;vertical-align:top;max-width:150px;" >
                <tbody><tr>
                                        <td bgcolor="#c12133" valign="top" style="padding-top:14px;padding-bottom:14px;padding-left:15px;padding-right:15px;">
                                                <a rel="nofollow" href="https://subscribe.ru/?ota=2IRHZXD6PJN7P44D53M3SZDIOOKNDZ4TJAWHNUF3XFDQNLXAY5NTNCHQ5CPW5P5KYP2H7OY6EYM&utm_source=subscribe-newsletters&utm_medium=email&utm_campaign=subscribe-newsletters">
                                                    <img src="https://subscribe.ru/img/new/index/logo.png" width="120" alt="Subscribe.ru" style="border-width:0;display:block;" IMAGE>
                        </a>
                    </td>
                </tr>
                </tbody></table>
            <!--[if (gte mso 9)|(IE)]>
            </td><td width="640" style="padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
            <![endif]-->
            <table style="border-spacing:0;width:100%;display:inline;vertical-align:top;max-width:640px;" >
                <tbody>
                <tr>
                    <td bgcolor="#d8dde0" valign="middle" align="left" style="padding-top:12px;padding-bottom:10px;padding-right:15px;padding-left:15px;font-family:'MS Sans Serif',Arial,Helvetica,Geneva;font-size:18px;line-height:22px; color:#222222;text-align:left;">
                                                         Вместо P.P.S. Выпуск №3830 от 31.03.2018
                                             </td>
                </tr>
            </tbody></table>
                    <!--[if (gte mso 9)|(IE)]>
                    </td>
                    </tr>
                    </table>
                    <![endif]-->
                </td>
            </tr>
            </tbody></table>
                    <!--[if (gte mso 9)|(IE)]>
                    </td>
                    </tr>
                    </table>
                    <![endif]-->
        </div>
        <!--/shapka-->
        
        <!--content begin-->
        <div style="max-width:800px; margin:0 auto; margin-top:15px;" lang="content">
            <!--[if (gte mso 9)|(IE)]>
            <table width="800" align="center" style="border-spacing:0;" >
                <tr>
                    <td style="padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
            <![endif]-->
            <table bgcolor="#ffffff" align="center" cellspacing="0" cellpadding="0" border="0" style="border-spacing:0;margin:0 auto;width:100%;max-width:800px;" >
                <tbody>
                <tr>
                    <td align="center">
    
            
    
    <table width="100%" summary="" cellspacing="0" cellpadding="0" border="0" bgcolor="#ffffff" style="background-color: #ffffff; background-image: ;">
    <tr valign="top" align="left">
    <td bgcolor="#ffffff" style="padding: 0; background-color: #ffffff; background-image: none; " class="two_column"><table width=600 bordercolor=black border=0 bgcolor=#500000 align=center><tr><td align=center><b><i><font size=4 face="Times New Roman"><font color=#FDC42E>В</font><font
color=#FBBF2B>м</font><font color=#F6B627>е</font><font color=#F2AE22>с</font><font color=#EDA41E>т</font><font color=#EBA01A>о </font><font color=#E69616>P.</font><font color=#E28B11>P.S.</font></i></b></td></tr></table>

<table width=600 bordercolor=#900000 border=1 bgcolor=#FFC830 align=center><tr><td align=center><b><i><font size=2 face="Times New Roman" color=#2F0000>Рассылка сайта <a href="http://redirect.subscribe.ru/rest.joke.vmestopps,37549/20180331113122/532614/m24424259/-/hohmochki.narod.ru"
rel="nofollow" color=#900000> Хохмочки</a></font></i></b></td></tr></table>

<table width=600 bordercolor=#900000 border=0 align=center bgcolor=#FFFFE0>
<tr><td>
<table width=590 bordercolor=#900000 border=0 align=center bgcolor=#FFFFE0>
<tr><td>
</tr>
<tr><td><font face="Times New Roman" color=#2F0000>
<div align=justify><br>

 / окончив пед учить детишек
 / я стану русскому в глуши
 / вот только жить мне на какие
 / жи ши<br><br>
<div align=center><font color=#900000>* * *</font></div><br>
А наш Петя возомнил себя настоящим мужчиной, даже побрился. Это уже потом мы ему объяснили, что настоящие мужики ноги не бреют.<br><br>
<div align=center><font color=#900000>* * *</font></div><br>
Вот назвали бы "Титаник" - "Г*вно", глядишь, всё бы и обошлось.<br><br>
<div align=center><font color=#900000>* * *</font></div><br>
Правильная женщина должна делать три вещи: приставать, покормить и не приставать.<br><br>
<div align=center><font color=#900000>* * *</font></div><br>
5 сезонов лоста, и ты в психушке.. несколько сезонов хауза, и ты там главврач!<br><br>

</div>
</font>
</tr>
</table>
</tr>
</table>

<table width=600 bordercolor=#900000 border=1 bgcolor=#FFC830 align=center>
<tr><td align=center>
<b><i><font size=2 face="Times New Roman" color=#2F0000>
Присылайте свои фразочки по адресу <a href="mailto:hohmochki@mail.ru" color=#900000>hohmochki@mail.ru</a><br>
Тираж выпуска 11454 экз.
</font></i></b><br>
<div style="margin-top:7px; margin-bottom:-3px;">
<div>
<a href="http://redirect.subscribe.ru/rest.joke.vmestopps,37549/20180331113122/532614/m24424259/-/vk.com/share.php?url=https://subscribe.ru/archive/rest.joke.vmestopps/201803/31113122.html" rel="nofollow"><img height="20" src="http://hohmochki.narod.ru/social/vk.png" width="20"></a>
<a href="https://twitter.com/share?url=https://subscribe.ru/archive/rest.joke.vmestopps/201803/31113122.html" data-text="Желаете блистать гранями? Россыпь прикольных афоризмов, цитат, фразочек для тех, кто любит
оригинально подписывать письма, остроумно поддерживать беседу и оставлять последнее слово за собой." data-lang="ru"><img height="20"
src="http://hohmochki.narod.ru/social/twitter.png" width="20"></a>
<a href="http://redirect.subscribe.ru/rest.joke.vmestopps,37549/20180331113122/532614/m24424259/-/www.facebook.com/sharer.php?u=https://subscribe.ru/archive/rest.joke.vmestopps/201803/31113122.html" rel="nofollow"><img height="20" src="http://hohmochki.narod.ru/social/facebook.png" width="20"></a>
<a href="https://plus.google.com/share?url=https://subscribe.ru/archive/rest.joke.vmestopps/201803/31113122.html"><img alt="Share on Google+" height="20" src="http://hohmochki.narod.ru/social/gplus-20.png" width="20"></a>
<a href="http://redirect.subscribe.ru/rest.joke.vmestopps,37549/20180331113122/532614/m24424259/-/info.flagcounter.com/KEn8" rel="nofollow"><img src="http://s11.flagcounter.com/count/KEn8/bg_FFFFFF/txt_000000/border_CCCCCC/columns_5/maxflags_20/viewers_0/labels_1/pageviews_0/flags_0/" width="1"
height="1" alt="Flag Counter" border="0"></a>
</div>
</div>
</td></tr>
</table>
<!-- " ' --></td>
        </tr>
    </table>
    
    
                                                  <!--lastissuelist-->
                    <br>
                    <table cellpadding="0" cellspacing="0" border="0" summary="" bgcolor="#ffffff" width="100%" style="border: 1px solid #e6e6e6;background-color:#ffffff; width: 100%;max-width: 800px;margin: 0px auto;" lang="x-lil" class="lil">
                        <tr><td height="20px"><font size="1" face="Arial, Helvetica, sans-serif" style="font-size: 13px">&nbsp;</font></td></tr>
                        <tr><td align="left" valign="middle" style="line-height:16px;" width="100%">
    <span style="background-color: #c12133;">&nbsp;</span>
    <font face="Arial" size="2" style="font-size: 13px">&nbsp;&nbsp;</font>
    <font color="#202020" face="Trebuchet MS, Arial, Helvetica, sans-serif" size="3" style="font-size: 16px; color: #202020;"><b>Прошлые выпуски</b></font>
    <br>
<a rel="nofollow" href="https://subscribe.ru/archive/rest.joke.vmestopps/201803/30081746.html?fromissue=0&ota=2IZDJXD6PJN7P44D53M3SZDIOOKNDZ4TJAWHNUF3XFDQNLXAY5NTNCHQ5CPW5P5KYP2H7OY6EYM&amp;utm_source=subscribe-newsletters&utm_medium=email&utm_campaign=subscribe-newsletters" style="color: #1c70a0;display: inline-block;width: 250px;padding: 10px;">
    <font color="#1c70a0" face="Arial, Helvetica, sans-serif" size="3" style="font-size: 14px; color: #1c70a0;">Вместо P.P.S. Выпуск №3829 от 30.03.2018</font></a><!--<font color="#7f7f7f" face="Arial, Helvetica, sans-serif" size="3" style="font-size: 14px; color:
#7f7f7f;">&nbsp;&nbsp;&nbsp;&nbsp;30&nbsp;ОҐОҐОҐОҐОҐ&nbsp;2018,&nbsp;08:17</font>
--><a rel="nofollow" href="https://subscribe.ru/archive/rest.joke.vmestopps/201803/28085034.html?fromissue=1&ota=2IZHJ7D6PJN7P44D53M3SZDIOOKNDZ4TJAWHNUF3XFDQNLXAY5NTNCHQ5CPW5P5KYP2H7OY6EYM&amp;utm_source=subscribe-newsletters&utm_medium=email&utm_campaign=subscribe-newsletters" style="color: #1c70a0;display: inline-block;width: 250px;padding: 10px;">
    <font color="#1c70a0" face="Arial, Helvetica, sans-serif" size="3" style="font-size: 14px; color: #1c70a0;">Вместо P.P.S. Выпуск №3828 от 28.03.2018</font></a><!--<font color="#7f7f7f" face="Arial, Helvetica, sans-serif" size="3" style="font-size: 14px; color:
#7f7f7f;">&nbsp;&nbsp;&nbsp;&nbsp;28&nbsp;ОҐОҐОҐОҐОҐ&nbsp;2018,&nbsp;08:50</font>
--><a rel="nofollow" href="https://subscribe.ru/archive/rest.joke.vmestopps/201803/27162536.html?fromissue=2&ota=2IBDJRD6PJN7P44D53M3SZDIOOKNDZ4TJAWHNUF3XFDQNLXAY5NTNCHQ5CPW5P5KYP2H7OY6EYM&amp;utm_source=subscribe-newsletters&utm_medium=email&utm_campaign=subscribe-newsletters" style="color: #1c70a0;display: inline-block;width: 250px;padding: 10px;">
    <font color="#1c70a0" face="Arial, Helvetica, sans-serif" size="3" style="font-size: 14px; color: #1c70a0;">Вместо P.P.S. Выпуск №3827 от 27.03.2018</font></a><!--<font color="#7f7f7f" face="Arial, Helvetica, sans-serif" size="3" style="font-size: 14px; color:
#7f7f7f;">&nbsp;&nbsp;&nbsp;&nbsp;27&nbsp;ОҐОҐОҐОҐОҐ&nbsp;2018,&nbsp;16:25</font>
-->    <a rel="nofollow" href="https://subscribe.ru/catalog/rest.joke.vmestopps?ota=2INDZ3D6PJN7P44D53M3SZDIOOKNDZ4TJAWHNUF3XFDQNLXAY5NTNCHQ5CPW5P5KYP2H7OY6EYM&utm_source=subscribe-newsletters&utm_medium=email&utm_campaign=subscribe-newsletters" style="color: #1c70a0; display: inline-block; width: 250px; padding: 10px;">
    <font color="#1c70a0" face="Arial, Helvetica, sans-serif" size="3" style="font-size: 14px; color: #1c70a0;"><strong>Все выпуски рассылки</strong></font></a></td>
</tr>
                        <tr><td height="20px"><font size="1" face="Arial, Helvetica, sans-serif" style="font-size: 13px">&nbsp;</font></td></tr>
                    </table>
                                
                </td>
                </tr>
            </tbody></table>
            <!--[if (gte mso 9)|(IE)]>
            </td>
            </tr>
            </table>
            <![endif]-->
        </div><!--/content end-->
        <!-- footer begin-->
        <div style="max-width:800px; margin:0 auto; margin-top:15px;" >
            <!--[if (gte mso 9)|(IE)]>
            <table width="800" align="center" style="border-spacing:0;" >
            <tr>
            <td style="padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
            <![endif]-->
            <table cellspacing="0" cellpadding="0" border="0" style="border-spacing:0;margin:0 auto;width:100%;max-width:800px;" >
                <tbody>
                <tr>
                <td align="left" style="font-family:'MS Sans Serif', Arial, Helvetica, sans-serif;color:#696969; font-size:12px; line-height:16px;padding:15px;">
                Если выпуск не&nbsp;отображается, вы&nbsp;можете прочесть его
                                        <a rel="nofollow" href="https://subscribe.ru/archive/rest.joke.vmestopps/201803/31113122.html?clearview&amp;amp;ota=2INDJ5D6PJN7P44D53M3SZDIOOKNDZ4TJAWHNUF3XFDQNLXAY5NTNCHQ5CPW5P5KYP2H7OY6EYM&utm_source=subscribe-newsletters&utm_medium=email&utm_campaign=subscribe-newsletters" style="color:#696969;">
                                        <span style="color:#696969;">на&nbsp;сайте</span></a>
                <br />
                <br />
                Это сообщение было отправлено на&nbsp;xserge@ukr.net потому, что вы&nbsp;подписались на&nbsp;рассылку
                                                        <a rel="nofollow" href="https://subscribe.ru/catalog/rest.joke.vmestopps?ota=2JVDJ5D6PJN7P44D53M3SZDIOOKNDZ4TJAWHNUF3XFDQNLXAY5NTNCHQ5CPW5P5KYP2H7OY6EYM&utm_source=subscribe-newsletters&utm_medium=email&utm_campaign=subscribe-newsletters" style="color: #888888;">
                                        rest.joke.vmestopps</a>
                                на&nbsp;subscribe.ru.<br />
                Чтобы гарантировать получение писем от&nbsp;нас&nbsp;— добавьте наш адрес в&nbsp;адресную книгу.
                <br />
                <br />
                Вы можете
                                                        <a rel="nofollow" href="https://subscribe.ru/member/Unsub?grp=rest.joke.vmestopps&amp;ota=2IZCZ3D6PJN7P44D53M3SZDIOOKNDZ4TJAWHNUF3XFDQNLXAY5NTNCHQ5CPW5P5KYP2H7OY6EYM&utm_source=subscribe-newsletters&utm_medium=email&utm_campaign=subscribe-newsletters" style="color: #696969;">
                                                            отказаться</a> от&nbsp;получения писем.<br />
                <br />
                                <a rel="nofollow" href="https://subscribe.ru/archive/rest.joke.vmestopps?ota=2IRHJ5D6PJN7P44D53M3SZDIOOKNDZ4TJAWHNUF3XFDQNLXAY5NTNCHQ5CPW5P5KYP2H7OY6EYM&utm_source=subscribe-newsletters&utm_medium=email&utm_campaign=subscribe-newsletters" style="color:#696969;">
                                    <span style="color:#696969;">Архив рассылки</span></a>
                                <a rel="nofollow" href="https://subscribe.ru/feedback/?xserge@ukr.net,rest.joke.vmestopps,20180331113122&utm_source=subscribe-newsletters&utm_medium=email&utm_campaign=subscribe-newsletters" style="color:#696969;">
                                    <span style="color:#696969;">Поддержка подписчиков</span></a>
                </td>
                </tr>
                </tbody></table>
            <!--[if (gte mso 9)|(IE)]>
            </td>
            </tr>
            </table>
            <![endif]-->
                        </div><!--/ footer end-->
                <img src="https://subscribe.ru/1.gif/subscribe/rest.joke.vmestopps,37549/20180331113122/=2EYY/m24424259" alt="" height="1" width="1" border="0" IMAGE>        
    
</center><!--/new main center tag-->
</body></html>

