Return-path: <gluck@mail.subscribe.ru>
Received: from [10.10.19.75] (helo=frv75.fwdcdn.com) by frv53.fwdcdn.com; Mon, 23 Apr 2018 22:26:08 +0300
Authentication-Result: IP=185.138.182.66; mail.from=gluck@mail.subscribe.ru; dkim=pass header.i= header.d=mail.fsndsy.ru; ID=1fAh6F-000O9Z-RU
Received-SPF: pass (frv75.fwdcdn.com: domain of mail.subscribe.ru designates 185.138.182.66 as permitted sender) client-ip=185.138.182.66; envelope-from=gluck@mail.subscribe.ru; helo=gato66.sndsy.ru;
Received: from gato66.sndsy.ru ([185.138.182.66])
	by frv75.fwdcdn.com with esmtps ID 1fAh6F-000O9Z-RU
	for xserge@ukr.net; Mon, 23 Apr 2018 22:26:07 +0300
Received: id 2A6ED48F771-1524511520
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=mail.fsndsy.ru; s=sndsy201706;
	t=1524511520; bh=bVXJM6CkFmLwQpnUlPIp30d+Z+TaMlOnpJOSV67Apag=;
	h=List-Id:List-Help:List-Subscribe:List-Unsubscribe:List-Archive:
	 List-Owner:List-Post:Message-Id:Date:From:To:X-Mailru-Msgtype:
	 Subject:MIME-Version:Content-Type;
	b=lVGS0inGOITAJMLWnyHHyqvp/1VFqEbS1Zk8tBaSs1GSkxLPWApQeniwG8pVV2OXd
	 6m/mmgH83IOTmlcno3TELAz8P+9OpXyRpd7cxzSjDwKnKilh/QouNdLA9Kj6IzB7Ou
	 JO4wdcWBNuFPtWEqXCCG8iB4HMQBBLD3Gz3qWL4w=
List-Id: <rest.joke.vmestopps.subscribe.ru>
List-Help: <https://subscribe.ru/catalog/rest.joke.vmestopps>
List-Subscribe: <mailto:rest.joke.vmestopps-sub@subscribe.ru>
List-Unsubscribe: <mailto:rest.joke.vmestopps-unsub@subscribe.ru>
List-Archive: <https://subscribe.ru/archive/rest.joke.vmestopps>
List-Owner: <mailto:rest.joke.vmestopps-owner@subscribe.ru>
List-Post: NO
Message-Id: <20180423222039.hux.24424259@24424259.rest.joke.vmestopps.subscribe>
Date: Mon, 23 Apr 2018 22:20:39 +0300
From: =?utf-8?Q?=22Subscribe=2ERu=22?= <namma24424259@subscribe.ru>
To: "rest.joke.vmestopps" <xserge@ukr.net> (24424259)
X-Mailru-Msgtype: rest.joke.vmestopps 
Subject: =?utf-8?Q?=D0=92=D0=BC=D0=B5=D1=81=D1=82=D0=BE=20?=
 =?utf-8?Q?P=2EP=2ES=2E=20?=
 =?utf-8?Q?=D0=92=D1=8B=D0=BF=D1=83=D1=81=D0=BA=20?=
 =?utf-8?Q?=E2=84=963848=20?=
 =?utf-8?Q?=D0=BE=D1=82=20?=
 =?utf-8?Q?23=2E04=2E2018?=
MIME-Version: 1.0
Content-Type: text/html;
  charset="utf-8"
X-Authentication-Results: mxs.ukr.net;
		dkim=pass  header.i= header.d=mail.fsndsy.ru envelope-from=gluck@mail.subscribe.ru;
		spf=pass (frv75.fwdcdn.com: domain of mail.subscribe.ru designates 185.138.182.66 as permitted sender) client-ip=185.138.182.66;
		dmarc=accept header-from=namma24424259@subscribe.ru
X-Ukrnet-Yellow: 1
X-Ukrnet-Flavor: coconut
X-Antivirus: Avast (VPS 180423-4, 23.04.2018), Inbound message
X-Antivirus-Status: Clean


    
<!--
~~*~~
-->
            
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!--[if !mso]><!-->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!--<![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
        <meta name="keywords" content="блистать грань россыпь прикольный афоризм цитата фразочка любить оригинальный подписывать письмо остроумный поддерживать беседа слово
подарки отдых знакомства цветы" />
    <meta name="author" content="hohmochki@mail.ru автор и ведущий рассылки Хохмочки" />
                <link rel="Shortcut Icon" type="image/x-icon" href="https://subscribe.ru/img/favicon.ico" />
        
    <title>Subscribe.Ru : Вместо P.P.S. Выпуск №3848 от 23.04.2018</title>
    <style type="text/css"><!-- a:link
{
	color: #900000; 
}
a:visited    { color: #2F0000 }
a:active     { color: #FF0000 }
body         { font-family: Times New Roman; background-color: #ebd2a5; color: #2F0000 }
hr           { height: 1; color: #900000 }
hr#2           { height: 2; color: #900000 }
table
{
   border-color: #900000;
}
h1, h2, h3, h4, h5, h6
{
	font-family: Arial Rounded MT Bold, Arial, Helvetica;
}
h1           { color: #2F0000 }
h2
{
	color: #2F0000; 
}
h3
{
	color: #2F0000; 
}
h4
{
	color: #2F0000;
}
h5
{
	color: #2F0000;
}
h6
{
	color: #2F0000;
} --></style>    <!--[if (gte mso 9)|(IE)]>
    <style type="text/css">
        table {border-collapse: collapse !important;}
    </style>
    <![endif]-->
    <style>
        @media only screen and (max-device-width: 800px) {
            body { background-color: #ffffff; }
        }
    </style>
</head>
<body style="margin:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;min-width:100%;background-color:#f5f7f8;" >
<!--main center tag-->
<center style="width:100%;table-layout:fixed;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;" lang="x-another">
            
                    <!--Реклама 600х90-->
                                <table class="pack_hide" style="margin: 0 auto;"><TR><TD>
                    <!-- 532715=532698=532724 -->

<tr><td><font size="1" face="Arial, Helvetica, sans-serif" style="font-size: 8px;">&nbsp;&nbsp;</font></td></tr>
<tr><td bgcolor="#ffffff" style="background-color:#ffffff; background-image:none; padding:0; margin:0;">

<table width="100%" border="0" cellspacing="0" cellpadding="0" style="background-image:none; padding:0; margin:0;">
<tr>
 <td bgcolor="#ffffff" style="background-color:#ffffff; background-image:none; padding:0; margin:0;" align="center">
   <table width="100%" border="0" cellspacing="10" cellpadding="0" style="background-image:none; padding:0; margin:0;">
  <tr>
   <td align="center" colspan="2" style="background-color:#ffffff; background-image:none; padding:0; margin:0;">

 
<table border="0" style="width: 750px; background-image:none; padding:0; margin:0;" class="items" align="center" width="750" cellpadding="0" cellspacing="5">
<tr valign="top">
<td align="left" valign="top" width="90" style="background-color:#ffffff; font-size:13px; background-image:none; padding:0; margin:0;"><a target="_blank" href="http://subs.link.subscribe.ru/subscribe/661245/24424259/rest.joke.vmestopps,37549/20180423222039/wbNso2B4kG5AXp0hns2AmQunuickuk"><img
hheight="75" border="0" width="75" style="border: 1px solid #ccc;" alt="Главное спортивное событие в серебре!"
  src="http://image.subscribe.ru/advert/14243/532715/img.png" /></a></td>
<td valign="top" width="153" style="background-color:#ffffff; background-image:none; padding:0; margin:0;"><a target="_blank" href="http://subs.link.subscribe.ru/subscribe/661245/24424259/rest.joke.vmestopps,37549/20180423222039/wbNso2B4kG5AXp0hns2AmQunuickuk" style="text-decoration: none;"><font
size="2" face="Trebuchet MS, Arial, Helvetica, sans-serif" color="#d83d24" style="font-size: 14px; text-decoration: none;"><b>
Главное спортивное событие в серебре!</b></font><br />  
</a>
<a target="_blank" style="text-decoration: none; font-size: 0.85em;" href="http://subs.link.subscribe.ru/subscribe/661245/24424259/rest.joke.vmestopps,37549/20180423222039/wbNso2B4kG5AXp0hns2AmQunuickuk"><font size="1" face="Trebuchet MS, Arial, Helvetica, sans-serif" color="#000" style="font-size:
11px; text-decoration: none;">
Коллекционная медаль из серебра посвященная Чемпионату Мира по Футболу за 799 рублей!</font></a><br/><br/>
</td>
<td width="10" style="background-color:#ffffff; background-image:none; padding:0; margin:0;">&nbsp;</td>

<td align="left" valign="top" width="90" style="background-color:#ffffff; font-size:13px; background-image:none; padding:0; margin:0;"><a target="_blank" href="http://subs.link.subscribe.ru/subscribe/661033/24424259/rest.joke.vmestopps,37549/20180423222039"><img hheight="75" border="0" width="75"
style="border: 1px solid #ccc;" alt="&quot;Супервклад&quot; БКС под 8,1% годовых в руб."
  src="http://image.subscribe.ru/advert/13902/532698/img.png" /></a></td>
<td valign="top" width="153" style="background-color:#ffffff; background-image:none; padding:0; margin:0;"><a target="_blank" href="http://subs.link.subscribe.ru/subscribe/661033/24424259/rest.joke.vmestopps,37549/20180423222039" style="text-decoration: none;"><font size="2" face="Trebuchet MS, Arial,
Helvetica, sans-serif" color="#d83d24" style="font-size: 14px; text-decoration: none;"><b>
"Супервклад" БКС под 8,1% годовых в руб.</b></font><br />  
</a>
<a target="_blank" style="text-decoration: none; font-size: 0.85em;" href="http://subs.link.subscribe.ru/subscribe/661033/24424259/rest.joke.vmestopps,37549/20180423222039"><font size="1" face="Trebuchet MS, Arial, Helvetica, sans-serif" color="#000" style="font-size: 11px; text-decoration: none;">
Плюс подарок - карта Visa Platinum c выгодным пакетом услуг. Вклад застрахован АСВ.</font></a><br/><br/>
</td>
<td width="10" style="background-color:#ffffff; background-image:none; padding:0; margin:0;">&nbsp;</td>

<td align="left" valign="top" width="90" style="background-color:#ffffff; font-size:13px; background-image:none; padding:0; margin:0;"><a target="_blank" href="http://subs.link.subscribe.ru/subscribe/660653/24424259/rest.joke.vmestopps,37549/20180423222039"><img hheight="75" border="0" width="75"
style="border: 1px solid #ccc;" alt="Forex через MetaTrader 4"
  src="http://image.subscribe.ru/advert/16/532724/img.png" /></a></td>
<td valign="top" width="153" style="background-color:#ffffff; background-image:none; padding:0; margin:0;"><a target="_blank" href="http://subs.link.subscribe.ru/subscribe/660653/24424259/rest.joke.vmestopps,37549/20180423222039" style="text-decoration: none;"><font size="2" face="Trebuchet MS, Arial,
Helvetica, sans-serif" color="#d83d24" style="font-size: 14px; text-decoration: none;"><b>
Forex через MetaTrader 4</b></font><br />  
</a>
<a target="_blank" style="text-decoration: none; font-size: 0.85em;" href="http://subs.link.subscribe.ru/subscribe/660653/24424259/rest.joke.vmestopps,37549/20180423222039"><font size="1" face="Trebuchet MS, Arial, Helvetica, sans-serif" color="#000" style="font-size: 11px; text-decoration: none;">
Наши клиенты знают как успешно работать на валютном рынке</font></a><br/><br/>
</td>
<td width="10" style="background-color:#ffffff; background-image:none; padding:0; margin:0;">&nbsp;</td>

</tr>
</table>



     </td>
   </tr>
   </table>
   
</td>
</tr>
</table>


</td></tr>

<tr><td><font size="1" face="Arial, Helvetica, sans-serif" style="font-size: 8px;">&nbsp;&nbsp;</font></td></tr>
<tr><td height="1" bgcolor="#b7b7b7"></td></tr>



                </TD></TR></table>
                        
                <!--shapka-->
        <div style="max-width:800px; margin:0 auto; margin-top:0px;" >
            <!--[if (gte mso 9)|(IE)]>
            <table width="800" align="center" style="border-spacing:0;" >
                <tr>
                    <td style="padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
            <![endif]-->
            
            <table align="center" cellspacing="0" cellpadding="0" border="0" style="border-spacing:0;margin:0 auto;width:100%;max-width:800px;" >
                <tbody>
                <tr>
                    <td bgcolor="#d8dde0" style="padding-top:0px;padding-bottom:0px;padding-right:0px;padding-left:0px;text-align:left;font-size:0;" >
            <!--[if (gte mso 9)|(IE)]>
            <table width="100%" style="border-spacing:0;" >
                <tr>
                    <td width="150" valign="top" style="padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
            <![endif]-->
            <table style="border-spacing:0;width:100%;display:inline-block;vertical-align:top;max-width:150px;" >
                <tbody><tr>
                                        <td bgcolor="#c12133" valign="top" style="padding-top:14px;padding-bottom:14px;padding-left:15px;padding-right:15px;">
                                                <a rel="nofollow" href="https://subscribe.ru/?ota=2IBHZRD6PJN7P44D53M3SZDIOOKNDZ4TJAWHNUF3XFDQNLXAY5NTNCHQ5CPW5P5K6P6DPGZGNYY&utm_source=subscribe-newsletters&utm_medium=email&utm_campaign=subscribe-newsletters">
                                                    <img src="https://subscribe.ru/img/new/index/logo.png" width="120" alt="Subscribe.ru" style="border-width:0;display:block;" IMAGE>
                        </a>
                    </td>
                </tr>
                </tbody></table>
            <!--[if (gte mso 9)|(IE)]>
            </td><td width="640" style="padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
            <![endif]-->
            <table style="border-spacing:0;width:100%;display:inline;vertical-align:top;max-width:640px;" >
                <tbody>
                <tr>
                    <td bgcolor="#d8dde0" valign="middle" align="left" style="padding-top:12px;padding-bottom:10px;padding-right:15px;padding-left:15px;font-family:'MS Sans Serif',Arial,Helvetica,Geneva;font-size:18px;line-height:22px; color:#222222;text-align:left;">
                                                         Вместо P.P.S. Выпуск №3848 от 23.04.2018
                                             </td>
                </tr>
            </tbody></table>
                    <!--[if (gte mso 9)|(IE)]>
                    </td>
                    </tr>
                    </table>
                    <![endif]-->
                </td>
            </tr>
            </tbody></table>
                    <!--[if (gte mso 9)|(IE)]>
                    </td>
                    </tr>
                    </table>
                    <![endif]-->
        </div>
        <!--/shapka-->
        
        <!--content begin-->
        <div style="max-width:800px; margin:0 auto; margin-top:15px;" lang="content">
            <!--[if (gte mso 9)|(IE)]>
            <table width="800" align="center" style="border-spacing:0;" >
                <tr>
                    <td style="padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
            <![endif]-->
            <table bgcolor="#ffffff" align="center" cellspacing="0" cellpadding="0" border="0" style="border-spacing:0;margin:0 auto;width:100%;max-width:800px;" >
                <tbody>
                <tr>
                    <td align="center">
    
            
    
    <table width="100%" summary="" cellspacing="0" cellpadding="0" border="0" bgcolor="#ffffff" style="background-color: #ffffff; background-image: ;">
    <tr valign="top" align="left">
    <td bgcolor="#ffffff" style="padding: 0; background-color: #ffffff; background-image: none; " class="two_column"><table width=600 bordercolor=black border=0 bgcolor=#500000 align=center><tr><td align=center><b><i><font size=4 face="Times New Roman"><font color=#FDC42E>В</font><font
color=#FBBF2B>м</font><font color=#F6B627>е</font><font color=#F2AE22>с</font><font color=#EDA41E>т</font><font color=#EBA01A>о </font><font color=#E69616>P.</font><font color=#E28B11>P.S.</font></i></b></td></tr></table>

<table width=600 bordercolor=#900000 border=1 bgcolor=#FFC830 align=center><tr><td align=center><b><i><font size=2 face="Times New Roman" color=#2F0000>Рассылка сайта <a
href="http://redirect.subscribe.ru/rest.joke.vmestopps,37549/20180423222039/532715=532698=532724/m24424259/-/hohmochki.narod.ru" rel="nofollow" color=#900000> Хохмочки</a></font></i></b></td></tr></table>

<table width=600 bordercolor=#900000 border=0 align=center bgcolor=#FFFFE0>
<tr><td>
<table width=590 bordercolor=#900000 border=0 align=center bgcolor=#FFFFE0>
<tr><td>
</tr>
<tr><td><font face="Times New Roman" color=#2F0000>
<div align=justify><br>

 / Я помню чудное мгновенье:
 / Перед тобой явилась я,
 / Как божество, как вдохновенье…
 / А ты не понял ни х*я.<br><br>
<div align=center><font color=#900000>* * *</font></div><br>

 / здесь вечеринка садо мазо
 / сказал швейцар кнутом грозя
 / к нам со своими синяками
 / нельзя<br><br>
<div align=center><font color=#900000>* * *</font></div><br>
Я не сексуально озабоченный. Я активный член общества...<br><br>
<div align=center><font color=#900000>* * *</font></div><br>
Если дать человеку ВСЁ, что он хочет, он захочет то, чего не хотел!!!<br><br>
<div align=center><font color=#900000>* * *</font></div><br>
Если человек обманул вас один раз, значит он подлец. Если человек обманул вас два раза, значит вы дурак.<br><br>

</div>
</font>
</tr>
</table>
</tr>
</table>

<table width=600 bordercolor=#900000 border=1 bgcolor=#FFC830 align=center>
<tr><td align=center>
<b><i><font size=2 face="Times New Roman" color=#2F0000>
Присылайте свои фразочки по адресу <a href="mailto:hohmochki@mail.ru" color=#900000>hohmochki@mail.ru</a><br>
Тираж выпуска 11442 экз.
</font></i></b><br>
<div style="margin-top:7px; margin-bottom:-3px;">
<div>
<a href="http://redirect.subscribe.ru/rest.joke.vmestopps,37549/20180423222039/532715=532698=532724/m24424259/-/vk.com/share.php?url=https://subscribe.ru/archive/rest.joke.vmestopps/201804/23222039.html" rel="nofollow"><img height="20" src="http://hohmochki.narod.ru/social/vk.png" width="20"></a>
<a href="https://twitter.com/share?url=https://subscribe.ru/archive/rest.joke.vmestopps/201804/23222039.html" data-text="Желаете блистать гранями? Россыпь прикольных афоризмов, цитат, фразочек для тех, кто любит
оригинально подписывать письма, остроумно поддерживать беседу и оставлять последнее слово за собой." data-lang="ru"><img height="20"
src="http://hohmochki.narod.ru/social/twitter.png" width="20"></a>
<a href="http://redirect.subscribe.ru/rest.joke.vmestopps,37549/20180423222039/532715=532698=532724/m24424259/-/www.facebook.com/sharer.php?u=https://subscribe.ru/archive/rest.joke.vmestopps/201804/23222039.html" rel="nofollow"><img height="20" src="http://hohmochki.narod.ru/social/facebook.png"
width="20"></a>
<a href="https://plus.google.com/share?url=https://subscribe.ru/archive/rest.joke.vmestopps/201804/23222039.html"><img alt="Share on Google+" height="20" src="http://hohmochki.narod.ru/social/gplus-20.png" width="20"></a>
<a href="http://redirect.subscribe.ru/rest.joke.vmestopps,37549/20180423222039/532715=532698=532724/m24424259/-/info.flagcounter.com/KEn8" rel="nofollow"><img src="http://s11.flagcounter.com/count/KEn8/bg_FFFFFF/txt_000000/border_CCCCCC/columns_5/maxflags_20/viewers_0/labels_1/pageviews_0/flags_0/"
width="1" height="1" alt="Flag Counter" border="0"></a>
</div>
</div>
</td></tr>
</table>
<!-- " ' --></td>
        </tr>
    </table>
    
    
                                                  <!--lastissuelist-->
                    <br>
                    <table cellpadding="0" cellspacing="0" border="0" summary="" bgcolor="#ffffff" width="100%" style="border: 1px solid #e6e6e6;background-color:#ffffff; width: 100%;max-width: 800px;margin: 0px auto;" lang="x-lil" class="lil">
                        <tr><td height="20px"><font size="1" face="Arial, Helvetica, sans-serif" style="font-size: 13px">&nbsp;</font></td></tr>
                        <tr><td align="left" valign="middle" style="line-height:16px;" width="100%">
    <span style="background-color: #c12133;">&nbsp;</span>
    <font face="Arial" size="2" style="font-size: 13px">&nbsp;&nbsp;</font>
    <font color="#202020" face="Trebuchet MS, Arial, Helvetica, sans-serif" size="3" style="font-size: 16px; color: #202020;"><b>Прошлые выпуски</b></font>
    <br>
<a rel="nofollow" href="https://subscribe.ru/archive/rest.joke.vmestopps/201804/20083051.html?fromissue=0&ota=2IZHZ7D6PJN7P44D53M3SZDIOOKNDZ4TJAWHNUF3XFDQNLXAY5NTNCHQ5CPW5P5K6P6DPGZGNYY&amp;utm_source=subscribe-newsletters&utm_medium=email&utm_campaign=subscribe-newsletters" style="color: #1c70a0;display: inline-block;width: 250px;padding: 10px;">
    <font color="#1c70a0" face="Arial, Helvetica, sans-serif" size="3" style="font-size: 14px; color: #1c70a0;">Вместо P.P.S. Выпуск №3847 от 20.04.2018</font></a><!--<font color="#7f7f7f" face="Arial, Helvetica, sans-serif" size="3" style="font-size: 14px; color:
#7f7f7f;">&nbsp;&nbsp;&nbsp;&nbsp;20&nbsp;ОҐОҐОҐОҐОҐОҐ&nbsp;2018,&nbsp;08:30</font>
--><a rel="nofollow" href="https://subscribe.ru/archive/rest.joke.vmestopps/201804/19183600.html?fromissue=1&ota=2IJDZXD6PJN7P44D53M3SZDIOOKNDZ4TJAWHNUF3XFDQNLXAY5NTNCHQ5CPW5P5K6P6DPGZGNYY&amp;utm_source=subscribe-newsletters&utm_medium=email&utm_campaign=subscribe-newsletters" style="color: #1c70a0;display: inline-block;width: 250px;padding: 10px;">
    <font color="#1c70a0" face="Arial, Helvetica, sans-serif" size="3" style="font-size: 14px; color: #1c70a0;">Вместо P.P.S. Выпуск №3846 от 19.04.2018</font></a><!--<font color="#7f7f7f" face="Arial, Helvetica, sans-serif" size="3" style="font-size: 14px; color:
#7f7f7f;">&nbsp;&nbsp;&nbsp;&nbsp;19&nbsp;ОҐОҐОҐОҐОҐОҐ&nbsp;2018,&nbsp;18:36</font>
--><a rel="nofollow" href="https://subscribe.ru/archive/rest.joke.vmestopps/201804/18131216.html?fromissue=2&ota=2IRHJZD6PJN7P44D53M3SZDIOOKNDZ4TJAWHNUF3XFDQNLXAY5NTNCHQ5CPW5P5K6P6DPGZGNYY&amp;utm_source=subscribe-newsletters&utm_medium=email&utm_campaign=subscribe-newsletters" style="color: #1c70a0;display: inline-block;width: 250px;padding: 10px;">
    <font color="#1c70a0" face="Arial, Helvetica, sans-serif" size="3" style="font-size: 14px; color: #1c70a0;">Вместо P.P.S. Выпуск №3845 от 18.04.2018</font></a><!--<font color="#7f7f7f" face="Arial, Helvetica, sans-serif" size="3" style="font-size: 14px; color:
#7f7f7f;">&nbsp;&nbsp;&nbsp;&nbsp;18&nbsp;ОҐОҐОҐОҐОҐОҐ&nbsp;2018,&nbsp;13:12</font>
-->    <a rel="nofollow" href="https://subscribe.ru/catalog/rest.joke.vmestopps?ota=2I5DJPD6PJN7P44D53M3SZDIOOKNDZ4TJAWHNUF3XFDQNLXAY5NTNCHQ5CPW5P5K6P6DPGZGNYY&utm_source=subscribe-newsletters&utm_medium=email&utm_campaign=subscribe-newsletters" style="color: #1c70a0; display: inline-block; width: 250px; padding: 10px;">
    <font color="#1c70a0" face="Arial, Helvetica, sans-serif" size="3" style="font-size: 14px; color: #1c70a0;"><strong>Все выпуски рассылки</strong></font></a></td>
</tr>
                        <tr><td height="20px"><font size="1" face="Arial, Helvetica, sans-serif" style="font-size: 13px">&nbsp;</font></td></tr>
                    </table>
                                
                </td>
                </tr>
            </tbody></table>
            <!--[if (gte mso 9)|(IE)]>
            </td>
            </tr>
            </table>
            <![endif]-->
        </div><!--/content end-->
        <!-- footer begin-->
        <div style="max-width:800px; margin:0 auto; margin-top:15px;" >
            <!--[if (gte mso 9)|(IE)]>
            <table width="800" align="center" style="border-spacing:0;" >
            <tr>
            <td style="padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
            <![endif]-->
            <table cellspacing="0" cellpadding="0" border="0" style="border-spacing:0;margin:0 auto;width:100%;max-width:800px;" >
                <tbody>
                <tr>
                <td align="left" style="font-family:'MS Sans Serif', Arial, Helvetica, sans-serif;color:#696969; font-size:12px; line-height:16px;padding:15px;">
                Если выпуск не&nbsp;отображается, вы&nbsp;можете прочесть его
                                        <a rel="nofollow" href="https://subscribe.ru/archive/rest.joke.vmestopps/201804/23222039.html?clearview&amp;amp;ota=2IFAJRD6PJN7P44D53M3SZDIOOKNDZ4TJAWHNUF3XFDQNLXAY5NTNCHQ5CPW5P5K6P6DPGZGNYY&utm_source=subscribe-newsletters&utm_medium=email&utm_campaign=subscribe-newsletters" style="color:#696969;">
                                        <span style="color:#696969;">на&nbsp;сайте</span></a>
                <br />
                <br />
                Это сообщение было отправлено на&nbsp;xserge@ukr.net потому, что вы&nbsp;подписались на&nbsp;рассылку
                                                        <a rel="nofollow" href="https://subscribe.ru/catalog/rest.joke.vmestopps?ota=2IRCJ7D6PJN7P44D53M3SZDIOOKNDZ4TJAWHNUF3XFDQNLXAY5NTNCHQ5CPW5P5K6P6DPGZGNYY&utm_source=subscribe-newsletters&utm_medium=email&utm_campaign=subscribe-newsletters" style="color: #888888;">
                                        rest.joke.vmestopps</a>
                                на&nbsp;subscribe.ru.<br />
                Чтобы гарантировать получение писем от&nbsp;нас&nbsp;— добавьте наш адрес в&nbsp;адресную книгу.
                <br />
                <br />
                Вы можете
                                                        <a rel="nofollow" href="https://subscribe.ru/member/Unsub?grp=rest.joke.vmestopps&amp;ota=2I5CZPD6PJN7P44D53M3SZDIOOKNDZ4TJAWHNUF3XFDQNLXAY5NTNCHQ5CPW5P5K6P6DPGZGNYY&utm_source=subscribe-newsletters&utm_medium=email&utm_campaign=subscribe-newsletters" style="color: #696969;">
                                                            отказаться</a> от&nbsp;получения писем.<br />
                <br />
                                <a rel="nofollow" href="https://subscribe.ru/archive/rest.joke.vmestopps?ota=2IZDJPD6PJN7P44D53M3SZDIOOKNDZ4TJAWHNUF3XFDQNLXAY5NTNCHQ5CPW5P5K6P6DPGZGNYY&utm_source=subscribe-newsletters&utm_medium=email&utm_campaign=subscribe-newsletters" style="color:#696969;">
                                    <span style="color:#696969;">Архив рассылки</span></a>
                                <a rel="nofollow" href="https://subscribe.ru/feedback/?xserge@ukr.net,rest.joke.vmestopps,20180423222039&utm_source=subscribe-newsletters&utm_medium=email&utm_campaign=subscribe-newsletters" style="color:#696969;">
                                    <span style="color:#696969;">Поддержка подписчиков</span></a>
                </td>
                </tr>
                </tbody></table>
            <!--[if (gte mso 9)|(IE)]>
            </td>
            </tr>
            </table>
            <![endif]-->
                        </div><!--/ footer end-->
                <img src="https://subscribe.ru/1.gif/subscribe/rest.joke.vmestopps,37549/20180423222039/=2EaB2EZu2EaK/m24424259" alt="" height="1" width="1" border="0" IMAGE>        
    
</center><!--/new main center tag-->
</body></html>

