Return-path: <gluck@mail.subscribe.ru>
Received: from [10.10.19.75] (helo=frv75.fwdcdn.com) by frv55.fwdcdn.com; Sat, 08 Dec 2018 09:06:57 +0200
Authentication-Result: IP=185.138.182.51; mail.from=gluck@mail.subscribe.ru; dkim=pass header.i= header.d=subscribe.ru; ID=1gVWhV-000Gkk-9L
Received-SPF: pass (frv75.fwdcdn.com: domain of mail.subscribe.ru designates 185.138.182.51 as permitted sender) client-ip=185.138.182.51; envelope-from=gluck@mail.subscribe.ru; helo=gato51.sndsy.ru;
Received: from gato51.sndsy.ru ([185.138.182.51])
	by frv75.fwdcdn.com with esmtps ID 1gVWhV-000Gkk-9L
	for xserge@ukr.net; Sat, 08 Dec 2018 09:06:57 +0200
Received: id 70C5091ADDC-1544252771
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=subscribe.ru; s=felis.201206;
	t=1544252771; bh=yCG3V6eKUmD+WEYQcwgPx1MpMez2/dLuRFSbgvRDdpg=;
	h=List-Id:List-Help:List-Subscribe:List-Unsubscribe:List-Archive:
	 List-Owner:List-Post:Message-Id:Date:From:To:X-Mailru-Msgtype:
	 Subject:MIME-Version:Content-Type;
	b=k5L+rc72qp9FHyHIFKesNozr+UKUBg8gpwRZVGwWxb9JBClboD/N+i4wNKGczCwdh
	 tBGpQgiMlFxjBtc4vusteO6hIOx1aZs2OrY4omZHfs+vX1AZTtQkHypvQg7dmdTvmP
	 QXASyTMXXi08OtyMQDz267z2EnRSExkdoW0oTH48=
List-Id: <rest.joke.vmestopps.subscribe.ru>
List-Help: <https://subscribe.ru/catalog/rest.joke.vmestopps>
List-Subscribe: <mailto:rest.joke.vmestopps-sub@subscribe.ru>
List-Unsubscribe: <mailto:rest.joke.vmestopps-unsub@subscribe.ru>
List-Archive: <https://subscribe.ru/archive/rest.joke.vmestopps>
List-Owner: <mailto:rest.joke.vmestopps-owner@subscribe.ru>
List-Post: NO
Message-Id: <20181208100408.hux.24424259@24424259.rest.joke.vmestopps.subscribe>
Date: Sat,  8 Dec 2018 10:04:09 +0300
From: =?utf-8?Q?=22Subscribe=2ERu=22?= <namma24424259@subscribe.ru>
To: "rest.joke.vmestopps" <xserge@ukr.net> (24424259)
X-Mailru-Msgtype: rest.joke.vmestopps 
Subject: =?utf-8?Q?=D0=92=D0=BC=D0=B5=D1=81=D1=82=D0=BE=20?=
 =?utf-8?Q?P=2EP=2ES=2E=20?=
 =?utf-8?Q?=D0=92=D1=8B=D0=BF=D1=83=D1=81=D0=BA=20?=
 =?utf-8?Q?=E2=84=963914=20?=
 =?utf-8?Q?=D0=BE=D1=82=20?=
 =?utf-8?Q?08=2E12=2E2018?=
MIME-Version: 1.0
Content-Type: text/html;
  charset="utf-8"
X-MXD: Yes
X-Authentication-Results: mxs.ukr.net;
		dkim=pass  header.i= header.d=subscribe.ru envelope-from=gluck@mail.subscribe.ru;
		spf=pass (frv75.fwdcdn.com: domain of mail.subscribe.ru designates 185.138.182.51 as permitted sender) client-ip=185.138.182.51;
		dmarc=accept header-from=namma24424259@subscribe.ru
X-Ukrnet-Yellow: 1
X-Ukrnet-Flavor: coconut


    
<!--
~~*~~
-->
            
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!--[if !mso]><!-->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!--<![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
        <meta name="keywords" content="блистать грань россыпь прикольный афоризм цитата фразочка любить оригинальный подписывать письмо остроумный поддерживать беседа слово подарки отдых знакомства цветы" />
    <meta name="author" content="hohmochki@mail.ru автор и ведущий рассылки Хохмочки" />
                <link rel="Shortcut Icon" type="image/x-icon" href="https://subscribe.ru/img/favicon.ico" />
        
    <title>Subscribe.Ru : Вместо P.P.S. Выпуск №3914 от 08.12.2018</title>
    <style type="text/css"><!-- a:link
{
	color: #900000; 
}
a:visited    { color: #2F0000 }
a:active     { color: #FF0000 }
body         { font-family: Times New Roman; background-color: #ebd2a5; color: #2F0000 }
hr           { height: 1; color: #900000 }
hr#2           { height: 2; color: #900000 }
table
{
   border-color: #900000;
}
h1, h2, h3, h4, h5, h6
{
	font-family: Arial Rounded MT Bold, Arial, Helvetica;
}
h1           { color: #2F0000 }
h2
{
	color: #2F0000; 
}
h3
{
	color: #2F0000; 
}
h4
{
	color: #2F0000;
}
h5
{
	color: #2F0000;
}
h6
{
	color: #2F0000;
} --></style>    <!--[if (gte mso 9)|(IE)]>
    <style type="text/css">
        table {border-collapse: collapse !important;}
    </style>
    <![endif]-->
    <style>
        @media only screen and (max-device-width: 800px) {
            body { background-color: #ffffff; }
        }
    </style>
</head>
<body style="margin:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;min-width:100%;background-color:#f5f7f8;" >
<!--main center tag-->
<center style="width:100%;table-layout:fixed;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;" lang="x-another">
            
                    <!-- 533295 -->

<tr><td><font size="1" face="Arial, Helvetica, sans-serif" style="font-size: 8px;">&nbsp;&nbsp;</font></td></tr>
<tr><td bgcolor="#ffffff" style="background-color:#ffffff; background-image:none; padding:0; margin:0;">

<table width="100%" border="0" cellspacing="0" cellpadding="0" style="background-image:none; padding:0; margin:0;">
<tr>
 <td bgcolor="#ffffff" style="background-color:#ffffff; background-image:none; padding:0; margin:0;" align="center">
 
<table width="100%" border="0" cellspacing="6" cellpadding="0" style="background-image:none; padding:0; margin:0;"><tr><td align="center" style="background-color:#ffffff; font-size:13px; background-image:none; padding:0; margin:0;">
<a href="http://subs.link.subscribe.ru/subscribe/668980/24424259/rest.joke.vmestopps,37549/20181208100408" style="text-decoration:none"><font face="Trebuchet MS, Arial, Helvetica, sans-serif" color="#1c70a0" size="2" style="font-size:13px"><b>А насколько вы готовы к ЕГЭ по английскому? Пройдите экспресс-тест.</b></font></a>
</td></tr></table>

   
</td>
</tr>
</table>


</td></tr>

<tr><td><font size="1" face="Arial, Helvetica, sans-serif" style="font-size: 8px;">&nbsp;&nbsp;</font></td></tr>
<tr><td height="1" bgcolor="#b7b7b7"></td></tr>



            <!--Реклама 600х90-->
                                <table class="pack_hide" style="margin: 0 auto;"><TR><TD>
                    <!-- 533275 -->

<tr><td><font size="1" face="Arial, Helvetica, sans-serif" style="font-size: 8px;">&nbsp;&nbsp;</font></td></tr>
<tr><td bgcolor="#ffffff" style="background-color:#ffffff; background-image:none; padding:0; margin:0;">

<table width="100%" border="0" cellspacing="0" cellpadding="0" style="background-image:none; padding:0; margin:0;">
<tr>
 <td bgcolor="#ffffff" style="background-color:#ffffff; background-image:none; padding:0; margin:0;" align="center">
   <table width="100%" border="0" cellspacing="10" cellpadding="0" style="background-image:none; padding:0; margin:0;">
  <tr>
   <td align="center" colspan="2" style="background-color:#ffffff; background-image:none; padding:0; margin:0;">

 

<table border="0" bordercolor="#f7fbff" bgcolor="#f7fbff" width="650" cellspacing="0" cellpadding="5" align="center" style="background-image:none; padding:0; margin:0;">
<tr>    
  <td width="120" valign="top" align="left" style="background-color:#ffffff; background-image:none; padding:0; margin:0;">
    <A href="http://subs.link.subscribe.ru/subscribe/668910/24424259/rest.joke.vmestopps,37549/20181208100408" target=_blank><img src="http://image.subscribe.ru/advert/16/533275/img.png" alt="Как рекламировать бизнес? Легко!" border="0"></a>
	  </td>    
  <td style="background-color:#ffffff; background-image:none; padding:0; margin:0; text-decoration:none;">
    <a href="http://subs.link.subscribe.ru/subscribe/668910/24424259/rest.joke.vmestopps,37549/20181208100408" target=_blank><font face="Trebuchet MS, Arial, Helvetica, sans-serif" color="#d83d24" size="3" style="font-size:16px"><strong>Как рекламировать бизнес? Легко!</strong></font></a><br>    
    <font face="Trebuchet MS, Arial, Helvetica, sans-serif" color="#222222" size="2" style="font-size:13px">Сервис для самостоятельного продвижения ваших товаров и услуг. Настройка рекламы с учетом особенностей вашего бизнеса.</font>
  </td>
</tr>    
</table>

     </td>
   </tr>
   </table>
   
</td>
</tr>
</table>


</td></tr>

<tr><td><font size="1" face="Arial, Helvetica, sans-serif" style="font-size: 8px;">&nbsp;&nbsp;</font></td></tr>
<tr><td height="1" bgcolor="#b7b7b7"></td></tr>



                </TD></TR></table>
                        
                <!--shapka-->
        <div style="max-width:800px; margin:0 auto; margin-top:0px;" >
            <!--[if (gte mso 9)|(IE)]>
            <table width="800" align="center" style="border-spacing:0;" >
                <tr>
                    <td style="padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
            <![endif]-->
            
            <table align="center" cellspacing="0" cellpadding="0" border="0" style="border-spacing:0;margin:0 auto;width:100%;max-width:800px;" >
                <tbody>
                <tr>
                    <td bgcolor="#d8dde0" style="padding-top:0px;padding-bottom:0px;padding-right:0px;padding-left:0px;text-align:left;font-size:0;" >
            <!--[if (gte mso 9)|(IE)]>
            <table width="100%" style="border-spacing:0;" >
                <tr>
                    <td width="150" valign="top" style="padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
            <![endif]-->
            <table style="border-spacing:0;width:100%;display:inline-block;vertical-align:top;max-width:150px;" >
                <tbody><tr>
                                        <td bgcolor="#c12133" valign="top" style="padding-top:14px;padding-bottom:14px;padding-left:15px;padding-right:15px;">
                                                <a rel="nofollow" href="https://subscribe.ru/?ota=2INAZXD6PJN7P44D53M3SZDIOOKNDZ4TJAWHNUF3XFDQNLXAY5NTNCHQ5CPW5P426PCBPAZWKZA&utm_source=subscribe-newsletters&utm_medium=email&utm_campaign=subscribe-newsletters">
                                                    <img src="https://subscribe.ru/img/new/index/logo.png" width="120" alt="Subscribe.ru" style="border-width:0;display:block;" IMAGE>
                        </a>
                    </td>
                </tr>
                </tbody></table>
            <!--[if (gte mso 9)|(IE)]>
            </td><td width="640" style="padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
            <![endif]-->
            <table style="border-spacing:0;width:100%;display:inline;vertical-align:top;max-width:640px;" >
                <tbody>
                <tr>
                    <td bgcolor="#d8dde0" valign="middle" align="left" style="padding-top:12px;padding-bottom:10px;padding-right:15px;padding-left:15px;font-family:'MS Sans Serif',Arial,Helvetica,Geneva;font-size:18px;line-height:22px; color:#222222;text-align:left;">
                                                         Вместо P.P.S. Выпуск №3914 от 08.12.2018
                                             </td>
                </tr>
            </tbody></table>
                    <!--[if (gte mso 9)|(IE)]>
                    </td>
                    </tr>
                    </table>
                    <![endif]-->
                </td>
            </tr>
            </tbody></table>
                    <!--[if (gte mso 9)|(IE)]>
                    </td>
                    </tr>
                    </table>
                    <![endif]-->
        </div>
        <!--/shapka-->
        
        <!--content begin-->
        <div style="max-width:800px; margin:0 auto; margin-top:15px;" lang="content">
            <!--[if (gte mso 9)|(IE)]>
            <table width="800" align="center" style="border-spacing:0;" >
                <tr>
                    <td style="padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
            <![endif]-->
            <table bgcolor="#ffffff" align="center" cellspacing="0" cellpadding="0" border="0" style="border-spacing:0;margin:0 auto;width:100%;max-width:800px;" >
                <tbody>
                <tr>
                    <td align="center">
    
            
    
    <table width="100%" summary="" cellspacing="0" cellpadding="0" border="0" bgcolor="#ffffff" style="background-color: #ffffff; background-image: ;">
    <tr valign="top" align="left">
    <td bgcolor="#ffffff" style="padding: 0; background-color: #ffffff; background-image: none; " class="two_column"><table width=600 bordercolor=black border=0 bgcolor=#500000 align=center><tr><td align=center><b><i><font size=4 face="Times New Roman"><font color=#FDC42E>В</font><font color=#FBBF2B>м</font><font color=#F6B627>е</font><font color=#F2AE22>с</font><font color=#EDA41E>т</font><font color=#EBA01A>о </font><font color=#E69616>P.</font><font color=#E28B11>P.S.</font></i></b></td></tr></table>

<table width=600 bordercolor=#900000 border=1 bgcolor=#FFC830 align=center><tr><td align=center><b><i><font size=2 face="Times New Roman" color=#2F0000>Рассылка сайта <a href="http://redirect.subscribe.ru/rest.joke.vmestopps,37549/20181208100408/533275=533295/m24424259/-/hohmochki.narod.ru" rel="nofollow" color=#900000> Хохмочки</a></font></i></b></td></tr></table>

<table width=600 bordercolor=#900000 border=0 align=center bgcolor=#FFFFE0>
<tr><td>
<table width=590 bordercolor=#900000 border=0 align=center bgcolor=#FFFFE0>
<tr><td>
</tr>
<tr><td><font face="Times New Roman" color=#2F0000>
<div align=justify><br>
Все женщины делятся на две категории. Одни любят мужчин, которые легко могут передвинуть шкаф, забить гвоздь, починить автомобиль. Другие любят мужчин, которые могут оплатить труд мужчин из первой категории.<br><br>
<div align=center><font color=#900000>* * *</font></div><br>
Готовь донос летом, а телегу - зимой.<br><br>
<div align=center><font color=#900000>* * *</font></div><br>
Положил детскую соску-пустышку рядом с плитой, она расплавилась и пристала к столу. Набрал в Гугле: как отодрать соску?... забыл, что искал...<br><br>
<div align=center><font color=#900000>* * *</font></div><br>
Жизнь она такая в общем и есть: проснулся, поработал, лёг спать. Кому повезло - тот ещё поел и потрахался.<br><br>
<div align=center><font color=#900000>* * *</font></div><br>
Села батарейка в мобильнике... И всё! Был человек – и нет человека!<br><br>

</div>
</font>
</tr>
</table>
</tr>
</table>

<table width=600 bordercolor=#900000 border=1 bgcolor=#FFC830 align=center>
<tr><td align=center>
<b><i><font size=2 face="Times New Roman" color=#2F0000>
Присылайте свои фразочки по адресу <a href="mailto:hohmochki@mail.ru" color=#900000>hohmochki@mail.ru</a><br>
Тираж выпуска 11373 экз.
</font></i></b><br>
<div style="margin-top:7px; margin-bottom:-3px;">
<div>
<a href="http://redirect.subscribe.ru/rest.joke.vmestopps,37549/20181208100408/533275=533295/m24424259/-/vk.com/share.php?url=https://subscribe.ru/archive/rest.joke.vmestopps/201812/08100408.html" rel="nofollow"><img height="20" src="http://hohmochki.narod.ru/social/vk.png" width="20"></a>
<a href="https://twitter.com/share?url=https://subscribe.ru/archive/rest.joke.vmestopps/201812/08100408.html" data-text="Желаете блистать гранями? Россыпь прикольных афоризмов, цитат, фразочек для тех, кто любит оригинально подписывать письма, остроумно поддерживать беседу и оставлять последнее слово за собой." data-lang="ru"><img height="20"
src="http://hohmochki.narod.ru/social/twitter.png" width="20"></a>
<a href="http://redirect.subscribe.ru/rest.joke.vmestopps,37549/20181208100408/533275=533295/m24424259/-/www.facebook.com/sharer.php?u=https://subscribe.ru/archive/rest.joke.vmestopps/201812/08100408.html" rel="nofollow"><img height="20" src="http://hohmochki.narod.ru/social/facebook.png" width="20"></a>
<a href="https://plus.google.com/share?url=https://subscribe.ru/archive/rest.joke.vmestopps/201812/08100408.html"><img alt="Share on Google+" height="20" src="http://hohmochki.narod.ru/social/gplus-20.png" width="20"></a>
<a href="http://redirect.subscribe.ru/rest.joke.vmestopps,37549/20181208100408/533275=533295/m24424259/-/info.flagcounter.com/KEn8" rel="nofollow"><img src="http://s11.flagcounter.com/count/KEn8/bg_FFFFFF/txt_000000/border_CCCCCC/columns_5/maxflags_20/viewers_0/labels_1/pageviews_0/flags_0/" width="1" height="1" alt="Flag Counter" border="0"></a>
</div>
</div>
</td></tr>
</table>
<!-- " ' --></td>
        </tr>
    </table>
    
    
                                                  <!--lastissuelist-->
                    <br>
                    <table cellpadding="0" cellspacing="0" border="0" summary="" bgcolor="#ffffff" width="100%" style="border: 1px solid #e6e6e6;background-color:#ffffff; width: 100%;max-width: 800px;margin: 0px auto;" lang="x-lil" class="lil">
                        <tr><td height="20px"><font size="1" face="Arial, Helvetica, sans-serif" style="font-size: 13px">&nbsp;</font></td></tr>
                        <tr><td align="left" valign="middle" style="line-height:16px;" width="100%">
    <span style="background-color: #c12133;">&nbsp;</span>
    <font face="Arial" size="2" style="font-size: 13px">&nbsp;&nbsp;</font>
    <font color="#202020" face="Trebuchet MS, Arial, Helvetica, sans-serif" size="3" style="font-size: 16px; color: #202020;"><b>Прошлые выпуски</b></font>
    <br>
<a rel="nofollow" href="https://subscribe.ru/archive/rest.joke.vmestopps/201811/24140548.html?fromissue=0&ota=2JRDJZD6PJN7P44D53M3SZDIOOKNDZ4TJAWHNUF3XFDQNLXAY5NTNCHQ5CPW5P426PCBPAZWKZA&amp;utm_source=subscribe-newsletters&utm_medium=email&utm_campaign=subscribe-newsletters" style="color: #1c70a0;display: inline-block;width: 250px;padding: 10px;">
    <font color="#1c70a0" face="Arial, Helvetica, sans-serif" size="3" style="font-size: 14px; color: #1c70a0;">Вместо P.P.S. Выпуск №3913 от 24.11.2018</font></a><!--<font color="#7f7f7f" face="Arial, Helvetica, sans-serif" size="3" style="font-size: 14px; color: #7f7f7f;">&nbsp;&nbsp;&nbsp;&nbsp;24&nbsp;ОҐОҐОҐОҐОҐОҐ&nbsp;2018,&nbsp;14:05</font>
--><a rel="nofollow" href="https://subscribe.ru/archive/rest.joke.vmestopps/201811/17123732.html?fromissue=1&ota=2IBDJTD6PJN7P44D53M3SZDIOOKNDZ4TJAWHNUF3XFDQNLXAY5NTNCHQ5CPW5P426PCBPAZWKZA&amp;utm_source=subscribe-newsletters&utm_medium=email&utm_campaign=subscribe-newsletters" style="color: #1c70a0;display: inline-block;width: 250px;padding: 10px;">
    <font color="#1c70a0" face="Arial, Helvetica, sans-serif" size="3" style="font-size: 14px; color: #1c70a0;">Вместо P.P.S. Выпуск №3912 от 17.11.2018</font></a><!--<font color="#7f7f7f" face="Arial, Helvetica, sans-serif" size="3" style="font-size: 14px; color: #7f7f7f;">&nbsp;&nbsp;&nbsp;&nbsp;17&nbsp;ОҐОҐОҐОҐОҐОҐ&nbsp;2018,&nbsp;12:37</font>
--><a rel="nofollow" href="https://subscribe.ru/archive/rest.joke.vmestopps/201811/12213350.html?fromissue=2&ota=2IBBZ7D6PJN7P44D53M3SZDIOOKNDZ4TJAWHNUF3XFDQNLXAY5NTNCHQ5CPW5P426PCBPAZWKZA&amp;utm_source=subscribe-newsletters&utm_medium=email&utm_campaign=subscribe-newsletters" style="color: #1c70a0;display: inline-block;width: 250px;padding: 10px;">
    <font color="#1c70a0" face="Arial, Helvetica, sans-serif" size="3" style="font-size: 14px; color: #1c70a0;">Вместо P.P.S. Выпуск №3911 от 12.11.2018</font></a><!--<font color="#7f7f7f" face="Arial, Helvetica, sans-serif" size="3" style="font-size: 14px; color: #7f7f7f;">&nbsp;&nbsp;&nbsp;&nbsp;12&nbsp;ОҐОҐОҐОҐОҐОҐ&nbsp;2018,&nbsp;21:33</font>
-->    <a rel="nofollow" href="https://subscribe.ru/catalog/rest.joke.vmestopps?ota=2IJDJTD6PJN7P44D53M3SZDIOOKNDZ4TJAWHNUF3XFDQNLXAY5NTNCHQ5CPW5P426PCBPAZWKZA&utm_source=subscribe-newsletters&utm_medium=email&utm_campaign=subscribe-newsletters" style="color: #1c70a0; display: inline-block; width: 250px; padding: 10px;">
    <font color="#1c70a0" face="Arial, Helvetica, sans-serif" size="3" style="font-size: 14px; color: #1c70a0;"><strong>Все выпуски рассылки</strong></font></a></td>
</tr>
                        <tr><td height="20px"><font size="1" face="Arial, Helvetica, sans-serif" style="font-size: 13px">&nbsp;</font></td></tr>
                    </table>
                                
                </td>
                </tr>
            </tbody></table>
            <!--[if (gte mso 9)|(IE)]>
            </td>
            </tr>
            </table>
            <![endif]-->
        </div><!--/content end-->
        <!-- footer begin-->
        <div style="max-width:800px; margin:0 auto; margin-top:15px;" >
            <!--[if (gte mso 9)|(IE)]>
            <table width="800" align="center" style="border-spacing:0;" >
            <tr>
            <td style="padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;" >
            <![endif]-->
            <table cellspacing="0" cellpadding="0" border="0" style="border-spacing:0;margin:0 auto;width:100%;max-width:800px;" >
                <tbody>
                <tr>
                <td align="left" style="font-family:'MS Sans Serif', Arial, Helvetica, sans-serif;color:#696969; font-size:12px; line-height:16px;padding:15px;">
                Если выпуск не&nbsp;отображается, вы&nbsp;можете прочесть его
                                        <a rel="nofollow" href="https://subscribe.ru/archive/rest.joke.vmestopps/201812/08100408.html?clearview&amp;amp;ota=2I5BZPD6PJN7P44D53M3SZDIOOKNDZ4TJAWHNUF3XFDQNLXAY5NTNCHQ5CPW5P426PCBPAZWKZA&utm_source=subscribe-newsletters&utm_medium=email&utm_campaign=subscribe-newsletters" style="color:#696969;">
                                        <span style="color:#696969;">на&nbsp;сайте</span></a>
                <br />
                <br />
                Это сообщение было отправлено на&nbsp;xserge@ukr.net потому, что вы&nbsp;подписались на&nbsp;рассылку
                                                        <a rel="nofollow" href="https://subscribe.ru/catalog/rest.joke.vmestopps?ota=2JVBZND6PJN7P44D53M3SZDIOOKNDZ4TJAWHNUF3XFDQNLXAY5NTNCHQ5CPW5P426PCBPAZWKZA&utm_source=subscribe-newsletters&utm_medium=email&utm_campaign=subscribe-newsletters" style="color: #888888;">
                                        rest.joke.vmestopps</a>
                                на&nbsp;subscribe.ru.<br />
                Чтобы гарантировать получение писем от&nbsp;нас&nbsp;— добавьте наш адрес в&nbsp;адресную книгу.
                <br />
                <br />
                Вы можете
                                                        <a rel="nofollow" href="https://subscribe.ru/member/Unsub?grp=rest.joke.vmestopps&amp;ota=2IZHZ5D6PJN7P44D53M3SZDIOOKNDZ4TJAWHNUF3XFDQNLXAY5NTNCHQ5CPW5P426PCBPAZWKZA&utm_source=subscribe-newsletters&utm_medium=email&utm_campaign=subscribe-newsletters" style="color: #696969;">
                                                            отказаться</a> от&nbsp;получения писем.<br />
                <br />
                                <a rel="nofollow" href="https://subscribe.ru/archive/rest.joke.vmestopps?ota=2IFDJND6PJN7P44D53M3SZDIOOKNDZ4TJAWHNUF3XFDQNLXAY5NTNCHQ5CPW5P426PCBPAZWKZA&utm_source=subscribe-newsletters&utm_medium=email&utm_campaign=subscribe-newsletters" style="color:#696969;">
                                    <span style="color:#696969;">Архив рассылки</span></a>
                                <a rel="nofollow" href="https://subscribe.ru/feedback/?xserge@ukr.net,rest.joke.vmestopps,20181208100408&utm_source=subscribe-newsletters&utm_medium=email&utm_campaign=subscribe-newsletters" style="color:#696969;">
                                    <span style="color:#696969;">Поддержка подписчиков</span></a>
                </td>
                </tr>
                </tbody></table>
            <!--[if (gte mso 9)|(IE)]>
            </td>
            </tr>
            </table>
            <![endif]-->
                        </div><!--/ footer end-->
                <img src="http://image.subscribe.ru/1.gif/subscribe/rest.joke.vmestopps,37549/20181208100408/=2EjD2EjX/m24424259" alt="" height="1" width="1" border="0">        
    
</center><!--/new main center tag-->
</body></html>

